<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
initial data for the neural network
### Hidden Layer:
intermediate layer between input and output layer and place where all the computation is done.
### Output Layer:
produce the result for given inputs.
![Neural Network](https://cdn-images-1.medium.com/max/1200/1*DW0Ccmj1hZ0OvSXi7Kz5MQ.jpeg)
### Neuron:
interactions between layers 


![Wikipedia Neuron Diagram](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Neuron.svg/500px-Neuron.svg.png)
### Weight:
![weight](https://miro.medium.com/max/1174/1*uz3wd5YeVYlU2JR8rE9VDA.png)
### Activation Function:
In Neural Network the activation function defines if given node should be “activated” or not based on the weighted sum. 
### Node Map:
A visual visual diagram of the architecture or "topology" of our neural network.
![A Mapping](http://jalammar.github.io/images/NNs_formula_no_bias.png)

### Perceptron:
A perceptron is just a single node or neuron of a neural network with nothing else. It can take any number of inputs and spit out an output. What a neuron does is it takes each of the input values, multplies each of them by a weight, sums all of these products up, and then passes the sum through what is called an "activation function" the result of which is the final value.


## Inputs -> Outputs

Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [151]:
"""
Import Statements
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt # to plot error during training

In [152]:
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [68]:
df.dtypes

x1    int64
x2    int64
y     int64
dtype: object

In [69]:
df.head()

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [114]:
# work in progess: 
# was not executed...
import numpy as np # helps with the math
import matplotlib.pyplot as plt # to plot error during training

# input data
inputs = np.array([[0, 0, 1],
                   [1, 0, 1],
                   [0, 1, 1],
                   [1, 1, 0]])
                   
# output data
outputs = np.array([[0], [1], [0], [1], [1]])

# create NeuralNetwork class
class NeuralNetwork:

    # intialize variables in class
    def __init__(self, inputs, outputs):
        self.inputs  = inputs
        self.outputs = outputs
        # initialize weights as .50 for simplicity
        self.weights = np.array([[.50], [.50]])
        self.error_history = []
        self.epoch_list = []

    #activation function ==> S(x) = 1/1+e^(-x)
    def sigmoid(self, x, deriv=False):
        if deriv == True:
            return x * (1 - x)
        return 1 / (1 + np.exp(-x))
 
    # going backwards through the network to update weights
    def error(self):
        self.error  = self.outputs - self.hidden
        delta = self.error * self.sigmoid(self.hidden, deriv=True)
        self.weights += np.dot(self.inputs.T, delta)

print(inputs)
print(outputs)

[[0 0 1]
 [1 0 1]
 [0 1 1]
 [1 1 0]]
[[0]
 [1]
 [0]
 [1]
 [1]]


In [120]:
inputs = np.array(df[['x1', 'x2']])
outputs = np.array(df[['y']])
print(inputs)
outputs

[[0 0]
 [1 0]
 [0 1]
 [1 1]]


array([[1],
       [1],
       [1],
       [0]])

### Sigmoid activation function and its derivative for updating weights

### Updating weights with derivative of sigmoid function:

![Sigmoid Function](https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Logistic-curve.svg/320px-Logistic-curve.svg.png)

In [125]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_dervative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [126]:
bias = 2 * np.random.random((1,1)) - 1
bias

array([[-0.1900324]])

In [127]:
# Initalize random weights for our 2 inputs:
weights = 2 * np.random.random((2,1))-1
weights

array([[ 0.89249102],
       [-0.41444224]])

In [128]:
# Calculate weighted sum of inputs and weights
weighted_sum = np.dot(inputs, weights) + bias
weighted_sum

array([[-0.1900324 ],
       [ 0.70245862],
       [-0.60447464],
       [ 0.28801638]])

In [134]:
# Output the activated value for the end of 1 training epoch
activated_output = sigmoid(weighted_sum)
activated_output  # True Values are [0,1,0,1]

array([[0.45263435],
       [0.66873265],
       [0.35332064],
       [0.57151044]])

In [135]:
# difference of output and true values to calculate error:
error = outputs - activated_output
error

array([[ 0.54736565],
       [ 0.33126735],
       [ 0.64667936],
       [-0.57151044]])

In [137]:
adjusted = error * sigmoid_dervative(activated_output)
adjusted

array([[ 0.13006503],
       [ 0.07420664],
       [ 0.15672746],
       [-0.13181771]])

In [138]:
weights += np.dot(inputs.T, adjusted)
weights

array([[ 0.83487995],
       [-0.38953249]])

In [148]:
# Update our weights 10,000 times - (fingers crossed that this process reduces error)
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights) + bias
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = outputs - activated_output
    
    adjustments = error * sigmoid_derivate(activated_output)
    
    # Update the bias
    bias += np.mean(error)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)
print('************************')
print("Output after training")
print(activated_output)


Weights after training
[[-13.94842159]
 [-13.94842159]]
************************
Output after training
[[1.        ]
 [0.99917111]
 [0.99917111]
 [0.0010544 ]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [84]:
d = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
d.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [149]:
"""
Import Statements
"""
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler, Normalizer


In [150]:
f = list(d)[:-1]

X = np.array(d[f])
y = np.array(d[['Outcome']])

MinMax = MinMaxScaler()
X = MinMax.fit_transform(X)

In [92]:
class Perceptron(object):
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_derivative(self, x):
        sx = self.sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        self.weights = 2 * np.random.random((X.shape[1], 1)) -1
    
        # Randomly Initialize Bias
        self.bias = 2 * np.random.random() - 1

        for i in range(self.niter):
        
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, self.weights) + self.bias
        
            # Activate!
            activated_output = self.sigmoid(weighted_sum)
        
            # Calc error
            error = y - activated_output
            
            # Update the Weights & Bias
            adjustments = error * self.sigmoid_derivative(activated_output)
            self.weights += np.dot(X.T, adjustments)
            self.bias += np.mean(error)

    def predict(self, X):
        """Return class label after unit step"""
        
        weighted_sum = np.dot(X, self.weights) + self.bias
        return np.round(self.sigmoid(weighted_sum))


In [141]:

model = Perceptron(niter = 10000)

# lets fit our model
model.fit(X, y)
test = model.predict(X)
test = test.astype(int)
test[:10]

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [142]:
# 
y[:10]

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [144]:
accuracy_score(test, y)

0.7643229166666666

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?